"""add activation token to users

Revision ID: ffdfd6a9592f
Revises: 2e1c817b7e6a
Create Date: 2026-09-01 12:35:43.835978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffdfd6a9592f'
down_revision: Union[str, None] = '2e1c817b7e6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('activation_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('activation_token_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_activation_token'), 'users', ['activation_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_activation_token'), table_name='users')
    op.drop_column('users', 'activation_token_expires_at')
    op.drop_column('users', 'activation_token')
    # ### end Alembic commands ###
